name: pycnic-blog
channels:
- defaults
dependencies:
- curl=7.52.1=0
- docutils=0.13.1=py36_0
- expat=2.1.0=0
- git=2.9.3=0
- gmp=6.1.0=0
- jinja2=2.9.4=py36_0
- libffi=3.2.1=1
- markdown=2.6.7=py36_0
- markupsafe=0.23=py36_2
- openssl=1.0.2k=0
- pandoc=1.15.0.6=0
- pip=9.0.1=py36_1
- pygments=2.1.3=py36_0
- python=3.6.0=0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- unidecode=0.04.19=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - blinker==1.4
  - feedgenerator==1.9
  - pelican==3.7.1
